version: '3.3'

services:


  nginx:
    image: quay.io/dtan4/nginx-basic-auth-proxy:latest
    ports:
      - 8085:80
      - 8090:8090
    environment:
      - BASIC_AUTH_USERNAME=omnilink
      - BASIC_AUTH_PASSWORD=omnilink2021
      - PROXY_PASS=http://kibana:5601
    networks:
      - eak

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    environment:
      - "cluster.routing.allocation.disk.threshold_enabled=false"
      - "discovery.type=single-node"
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - ELASTIC_PASSWORD=LkU5qqCTsCbfSCFd
      # - xpack.security.enabled=true
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - 9200:9200
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://elasticsearch:9200']
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - eak

  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.0
    environment:
      - SERVER_HOST=0.0.0.0
      - KIBANA_ELASTICSEARCH_URL=elasticsearch
      - XPACK_SECURITY_ENABLED=true
      # - ELASTICSEARCH_USERNAME=kibana
      # - ELASTICSEARCH_PASSWORD=kibanachangeme
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - 5601:5601
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://kibana:5601']
      interval: 10s
      timeout: 5s
      retries: 1
      #  depends_on:
      # elasticsearch:
      # condition: service_healthy
    networks:
      - eak
        
  apm-server:
    image: docker.elastic.co/apm/apm-server:7.8.0
    volumes:
      - type: bind
        source: ./extensions/apm-server/config/apm-server.yml
        target: /usr/share/apm-server/apm-server.yml
        read_only: true
    ports:
      - '8200:8200'
    # environment:
    #   - output.elasticsearch.hosts=['http://elasticsearch:9200']
    #   - apm-server.host="0.0.0.0:8200"
    #   - apm-server.secret_token="xxVpmQB2HMzCL9PgBHVrnxjNXXw5J7bd79DFm6sjBJR5HPXDhcF8MSb3vv4bpg44"
    #   - setup.kibana.host="kibana:5601"
    #   - setup.template.enabled=true
    #   - logging.to_files=false
    # depends_on:
    # elasticsearch:
    #   condition: service_healthy
    #  kibana:
    #    condition: service_healthy
    networks:
      - eak

networks: 
  eak:

volumes:
  elasticsearch:
